console.log("My First Console Project");
var firstname="shreyan";
var lastname="agarwal";
var fullname=firstname.concat(lastname); 
console.log(fullname);
var number1="15";
console.log(number1);
var number2="5";
console.log(number2);
var addded_number=number1+number2;
console.log(addded_number);
var subtracted_number=number1-number2;
console.log(subtracted_number);